// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://mbaeejjxujzzfvrhurcy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1iYWVlamp4dWp6emZ2cmh1cmN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MjA1NjYsImV4cCI6MjA2NjI5NjU2Nn0.PenTqYKE-yb4WeWvLhR2QWs8KeDuXtsTYM9uX7_meHU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);